---
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-cli
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  BW_HOST: {{ .Values.bitwarden.host | b64enc }}
  BW_USER: {{ .Values.bitwarden.username | b64enc }}
  BW_PASSWORD: {{ .Values.bitwarden.password | b64enc }}
  BW_CLIENTID: {{ .Values.bitwarden.clientid | b64enc }}
  BW_CLIENTSECRET: {{ .Values.bitwarden.clientsecret | b64enc }}
