# Values for app-ingress chart
# Set your domain here
domain: homelab.schwfam.org

issuer:
  name: letsencrypt-dns-cloudflare
  accountSecret: letsencrypt-account-key

externalSecrets:
  refreshInterval: 1h
  namespace: 'cert-manager'

secretStore:
  name: bitwarden-notes
  namespace: external-secrets

# TODO: configure this in custom values
publicIP:
  namespace: metallb-system
