---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: nas-smb-storageclass
provisioner: smb.csi.k8s.io
parameters:
    source: "{{ .Values.smbSource }}"
    # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
    # with PV name under source
    csi.storage.k8s.io/provisioner-secret-name: "{{ .Values.externalSecret.secretName }}"
    csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Values.externalSecret.namespace }}"
    csi.storage.k8s.io/node-stage-secret-name: "{{ .Values.externalSecret.secretName }}"
    csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Values.externalSecret.namespace }}"
volumeBindingMode: Immediate
reclaimPolicy: Retain
mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid={{ .Values.uid }}
    - gid={{ .Values.gid }}