apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-pool
  namespace: {{ .Values.publicIP.namespace | quote }}
spec:
  addresses:
    - {{ .Values.publicIP.address }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: {{ .Values.publicIP.namespace | quote }}
spec:
  ipAddressPools:
    - ingress-pool