# Loop over services defined in values.yaml and create a Service for each
{{- $releaseNamespace := .Release.Namespace }}
{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
  namespace: {{ $releaseNamespace }}
spec:
  ports:
  - name: {{ ternary "https" "http" .https }}
    protocol: TCP
    port: {{ ternary "443" "80" .https }}
    targetPort: {{ .port }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .name }}-ep
  labels:
    kubernetes.io/service-name: {{ .name | quote }}
addressType: IPv4
ports:
  - name: {{ ternary "https" "http" .https }}
    protocol: TCP
    port: {{ .port }}
endpoints:
  - addresses:
      - {{ .ip | quote }}
    conditions:
      ready: true
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-http
  namespace: {{ $releaseNamespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
{{- range .Values.services }}
{{- if not .https }}
        - {{ .hostname | quote }}
{{- end}}
{{- end }}
      secretName: homelab-wildcard-tls-http
  rules:
{{- range .Values.services }}
{{- if not .https }}
    - host: {{ .hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name | quote }}
                port:
                  number: {{ .port }}
{{- end }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-https
  namespace: {{ $releaseNamespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
{{- range .Values.services }}
{{- if .https }}
        - {{ .hostname | quote }}
{{- end}}
{{- end }}
      secretName: homelab-wildcard-tls-https
  rules:
{{- range .Values.services }}
{{- if .https }}
    - host: {{ .hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name | quote }}
                port:
                  number: {{ .port }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: {{ .Values.ingress.namespace }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.ingress.ip }}
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx