apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-bootstrap-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-bootstrap-certificate
  namespace: {{ .Release.Namespace }}
spec:
  commonName: cert-manager-bitwarden-tls
  isCA: true
  secretName: bitwarden-tls-ca
  subject:
    organizations:
      - external-secrets.io
  dnsNames:
    - external-secrets-bitwarden-sdk-server.{{ .Release.Namespace }}.svc.cluster.local
    - bitwarden-sdk-server.{{ .Release.Namespace }}.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bitwarden-bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bitwarden-certificate-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: bitwarden-tls-ca
---
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: {{ .Release.Namespace }}
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.{{ .Release.Namespace }}.svc.cluster.local
    - external-secrets-bitwarden-sdk-server.{{ .Release.Namespace }}.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
    rotationPolicy: Always
  duration: 168h # 7d
  renewBefore: 24h # 1d
  issuerRef:
    name: bitwarden-certificate-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-css-certs
  namespace: {{ .Release.Namespace }}
spec:
  secretName: bitwarden-css-certs
  dnsNames:
    - bitwarden-secrets-manager.{{ .Release.Namespace }}.svc.cluster.local
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
    rotationPolicy: Always
  usages:
    - client auth
  issuerRef:
    name: bitwarden-certificate-issuer
    kind: Issuer
    group: cert-manager.io