apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secret.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.secret.name | quote }}
    creationPolicy: Owner
  data:
    - secretKey: unseal_keys
      sourceRef:
        storeRef:
          name: {{ .Values.externalSecrets.secretStore.name | quote }}
          kind: ClusterSecretStore
      remoteRef:
        key: {{ .Values.externalSecrets.secret.remoteKey | quote }}
        property: notes
